### ISSUE TITLE
visibilitychange 의 polyfill 검토

### ISSUE THREAD

**Issue by dduskim** [daumcorp/web2app#9]
A shim for the Page Visibility API
* https://github.com/addyosmani/visibly.js

**Comment by ragiragi** [comment]
결국 window 객체의 `focus`, `blur` 이벤트를 사용하는 것 같네요. 모바일 환경에서 잘 동작하나요?

**Comment by dduskim** [comment]
모바일에서는 잘되는지, Page Visibility API의 지원정도는 어느정도이고 미지원시 어느정도나 사용될지,
의존성을 추가하고 코드량을 늘리면서 사용할 필요가 있는건지  를 검토해보려한건데

모바일에서 잘 안되고(안드로이드 미지원브라우저)...에서 끝나네요
iOS7 에서 잘 된다 하더라도 현재 pagehide 이벤트로 처리가 가능하므로 이슈 종료처리 하도록 하겠습니다 ~
